export interface ProductData {
  id: string;
  name: string;
  price: number;
  oldPrice?: number;
  img: string;
  tag?: string;
  details?: Record<string, string>;
  qtdOptions?: number[];
  category?: string;
}

export const PROMO_PRODUCTS: ProductData[] = [
  {
    id: 'p1',
    name: 'Arroz Don Pato (25kg)',
    price: 1850,
    oldPrice: 2100,
    tag: 'POUPANÇA',
    img: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '25 kg', Marca: 'Don Pato', Origem: 'Moçambique', Stock: 'Em Stock', Validade: '24 meses' },
    qtdOptions: [1, 2, 5, 10],
    category: 'cereais',
  },
  {
    id: 'p2',
    name: 'Óleo Vegetal Somol (20L)',
    price: 2400,
    oldPrice: 2650,
    tag: 'DESTAQUE',
    img: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=400',
    details: { Volume: '20 L', Tipo: 'Vegetal Refinado', Marca: 'Somol', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 4, 6],
    category: 'mercearia',
  },
  {
    id: 'p9',
    name: 'Leite UHT (12x1L)',
    price: 1100,
    oldPrice: 1350,
    tag: 'ESSENCIAL',
    img: 'https://images.unsplash.com/photo-1563636619-e910ef2a844b?auto=format&fit=crop&q=80&w=400',
    details: { Formato: 'Caixa 12 unid.', Conteúdo: '1L cada', Tipo: 'Inteiro UHT', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 3, 6],
    category: 'laticinios',
  },
  {
    id: 'p10',
    name: 'Farinha de Trigo (50kg)',
    price: 2800,
    oldPrice: 3100,
    tag: 'VOLUME',
    img: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '50 kg', Tipo: 'Especial T55', Uso: 'Panificação', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 3, 5],
    category: 'cereais',
  },
];

export const ALL_PRODUCTS: ProductData[] = [
  ...PROMO_PRODUCTS,
  {
    id: 'p3',
    name: 'Farinha Milho (10kg)',
    price: 750,
    img: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '10 kg', Tipo: 'Milho branco moído', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 5, 10],
    category: 'cereais',
  },
  {
    id: 'p4',
    name: 'Caixa Tomate (15kg)',
    price: 800,
    img: 'https://images.unsplash.com/photo-1582284540020-8acbe03f4924?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '15 kg', Origem: 'Nacional', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 3],
    category: 'vegetais',
  },
  {
    id: 'p5',
    name: 'Açúcar Castanho (10kg)',
    price: 900,
    img: 'https://images.unsplash.com/photo-1581448670402-318a73a39f82?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '10 kg', Tipo: 'Castanho refinado', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 5, 10],
    category: 'mercearia',
  },
  {
    id: 'p6',
    name: 'Feijão Manteiga (5kg)',
    price: 450,
    img: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '5 kg', Origem: 'Nacional', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 4, 8],
    category: 'leguminosas',
  },
  {
    id: 'p7',
    name: 'Batata Nacional (10kg)',
    price: 550,
    img: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '10 kg', Origem: 'Sussundenga', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 5],
    category: 'vegetais',
  },
  {
    id: 'p8',
    name: 'Cebola Branca (10kg)',
    price: 480,
    img: 'https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '10 kg', Origem: 'Nacional', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 5, 10],
    category: 'vegetais',
  },
  {
    id: 'p11',
    name: 'Detergente OMO (5kg)',
    price: 1100,
    img: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '5 kg', Tipo: 'Pó', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 4],
    category: 'higiene',
  },
  {
    id: 'p12',
    name: 'Água (24x0.5L)',
    price: 380,
    img: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&q=80&w=400',
    details: { Formato: '24 garrafas x 0.5L', Tipo: 'Mineral', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 5, 10],
    category: 'bebidas',
  },
  {
    id: 'p13',
    name: 'Sal Refinado (20kg)',
    price: 350,
    img: 'https://images.unsplash.com/photo-1518110903427-0244721df33b?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '20 kg', Tipo: 'Refinado iodado', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 5, 10],
    category: 'mercearia',
  },
  {
    id: 'p14',
    name: 'Frango (fardo 10kg)',
    price: 1650,
    img: 'https://images.unsplash.com/photo-1501200291289-c5a76c232e5f?auto=format&fit=crop&q=80&w=400',
    details: { Peso: '10 kg', Tipo: 'Congelado', Marca: 'Abílio & Irmãos', Stock: 'Em Stock' },
    qtdOptions: [1, 2, 3, 5],
    category: 'carnes',
  },
];

export const CATEGORIES = [
  { id: 'todos', label: 'Todos', emoji: '🏪' },
  { id: 'cereais', label: 'Cereais', emoji: '🌾' },
  { id: 'vegetais', label: 'Vegetais', emoji: '🥬' },
  { id: 'carnes', label: 'Carnes', emoji: '🥩' },
  { id: 'mercearia', label: 'Mercearia', emoji: '🧂' },
  { id: 'higiene', label: 'Higiene', emoji: '🧴' },
  { id: 'bebidas', label: 'Bebidas', emoji: '💧' },
  { id: 'laticinios', label: 'Laticínios', emoji: '🥛' },
  { id: 'leguminosas', label: 'Leguminosas', emoji: '🫘' },
];

export const RECIPES = [
  {
    id: 1,
    title: 'Matapa Tradicional',
    description: 'O prato mais icónico de Moçambique, feito com folhas de mandioca, amendoim e leite de coco.',
    img: 'https://images.unsplash.com/photo-1604909052743-cd1c64e1c999?auto=format&fit=crop&q=80&w=800',
    time: '90 min',
    difficulty: 'Médio',
    servings: 6,
    ingredients: [
      '500g folhas de mandioca piladas',
      '200g amendoim torrado moído',
      '400ml leite de coco',
      '300g camarão ou caranguejo',
      '2 cebolas picadas',
      '4 dentes de alho',
      'Sal e piri-piri q.b.',
    ],
    steps: [
      'Pila as folhas de mandioca até ficarem bem finas.',
      'Cozinha a mandioca com água até secar completamente (45-60 min).',
      'Adiciona o amendoim moído e mistura bem.',
      'Junta o leite de coco e o marisco.',
      'Cozinha em lume brando por mais 30 minutos, mexendo sempre.',
      'Tempera com sal e piri-piri. Serve com arroz branco.',
    ],
  },
  {
    id: 2,
    title: 'Caril de Peixe',
    description: 'Caril aromático com peixe fresco, tomate e especiarias típicas moçambicanas.',
    img: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?auto=format&fit=crop&q=80&w=800',
    time: '45 min',
    difficulty: 'Fácil',
    servings: 4,
    ingredients: [
      '800g peixe fresco (robalo ou garoupa)',
      '2 tomates maduros',
      '1 cebola grande',
      '3 dentes de alho',
      '400ml leite de coco',
      '2 colheres caril em pó',
      'Limão, coentros, sal',
    ],
    steps: [
      'Tempera o peixe com limão, sal e alho.',
      'Refoga a cebola e alho em óleo até dourar.',
      'Adiciona o tomate e o caril, cozinha 5 minutos.',
      'Junta o leite de coco e deixa ferver.',
      'Adiciona o peixe e cozinha 15 minutos em lume médio.',
      'Finaliza com coentros frescos. Serve com arroz.',
    ],
  },
  {
    id: 3,
    title: 'Frango Grelhado Piri-Piri',
    description: 'Frango marinado em molho piri-piri caseiro, grelhado na brasa.',
    img: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c1?auto=format&fit=crop&q=80&w=800',
    time: '60 min',
    difficulty: 'Fácil',
    servings: 4,
    ingredients: [
      '1 frango inteiro partido',
      '6 piri-piris vermelhos',
      '4 dentes de alho',
      'Sumo de 2 limões',
      '4 colheres de azeite',
      'Sal, colorau, orégãos',
    ],
    steps: [
      'Tritura os piri-piris com alho, limão e azeite.',
      'Marina o frango na mistura durante 2h no frigorífico.',
      'Grelha em brasas médias, virando a cada 10 minutos.',
      'Pincela com a marinada ao longo da cozedura.',
      'Serve com batata frita e salada.',
    ],
  },
  {
    id: 4,
    title: 'Arroz de Coco',
    description: 'Arroz cremoso cozinhado em leite de coco, acompanhamento perfeito.',
    img: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&q=80&w=800',
    time: '30 min',
    difficulty: 'Fácil',
    servings: 4,
    ingredients: [
      '2 chávenas de arroz',
      '400ml leite de coco',
      '2 chávenas de água',
      '1 colher de sal',
      '1 pau de canela',
    ],
    steps: [
      'Lava o arroz até a água sair limpa.',
      'Mistura o leite de coco com a água e o sal.',
      'Coloca o arroz e o pau de canela na panela.',
      'Cozinha em lume médio-baixo com tampa durante 20 min.',
      'Remove o pau de canela e serve.',
    ],
  },
];
